version: '3'
services:
  octoprint-klipper:
    image: "dallerman/OctoPrint-Klipper-Unraid:amd64"
    container_name: "OctoPrint-Klipper-Unraid"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    ports:
      - "5000:5000"
    volumes:
      - "/mnt/user/appdata/Octoprint:/home/octoprint/.octoprint"
    environment:
      TZ: "Europe/Berlin"
    restart: unless-stopped
